apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-path-provisioner
provisioning:
  diskSelector:
    match: "!system_disk && disk.size > 250u * GiB"
  minSize: 250GiB
  grow: true
filesystem:
  type: xfs
