apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrepository-prometheus-community.yaml
  - helmrepository-grafana.yaml
  - helmrepository-grafana-community.yaml
  - kube-prometheus-stack.yaml
  - alertmanagerconfig-email.yaml
  - prometheusrule-local-path-storage.yaml
  - ./logging
  - grafana-tailscale-ingress.yaml
