apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: document-portal-data
  namespace: document-portal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
