apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - portfolio-tailscale-ingress.yaml

images:
  - name: ghcr.io/dgsuma/enhanced-portfolio-site
    newTag: 2da57cb7b21c
